name: Docker Publish # Workflow Name

on: # What event triggers this workflow & where
  push: # push event/action
    branches: # list of branches this that trigger the workflow
    - main
permissions: # setting permissions 
  contents: read # can read the repository contents
  packages: write # can push packages to GitHub Container Registry

jobs: # Defining jobs which are composed of steps and actions executed on a single runner
  build-and-push: # job name
    runs-on: ubuntu-latest # what flavor of runner the job will run on. Latest version of ubuntu selected.
    steps: # defining the steps that will run
    - uses: actions/checkout@v6 # first step. checks out the repo on the runner.
    - name: Log in to the Container Registry # naming step 2
      uses: docker/login-action@v3 # calling github action to log into registry with credentials
      with: # specifying which registry and what credentials are used to log in
        registry: ghcr.io # github registry
        username: ${{ github.actor }} # current user 
        password: ${{ secrets.GITHUB_TOKEN }} # built in github token. Destroyed and rebuilt for each runner
    - name: Build and push Docker image # running commands to build image and push to registry
      run: | # commands to run
        docker build . --tag ghcr.io/rikg215/skills-publish-docker-images/stackoverflown:main
        docker push ghcr.io/rikg215/skills-publish-docker-images/stackoverflown:main
